import "./globals.css"
import { Root } from "./components/root";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" suppressHydrationWarning={false}>
      <body>
        <Root />
      </body>
    </html>
  )
}
