/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  worldcreator: {
    gameMode: string;
    difficulty: string;
    cheatsEnabled: boolean;
    generateStructures: boolean;
    bonusChestEnabled: boolean;
    generatorOptionsHolder: {
      shouldGenerateStructures: boolean;
      hasBonusChest: boolean;
      seed: number;
      isLegacyCustomizedType: boolean;
      [k: string]: unknown;
    };
    worldType: string;
    [k: string]: unknown;
  };
  gamerules: {
    entries: {
      globalSoundEvents: boolean;
      tntExplosionDropDecay: boolean;
      enderPearlsVanishOnDeath: boolean;
      doFireTick: boolean;
      maxCommandChainLength: number;
      doVinesSpread: boolean;
      disableElytraMovementCheck: boolean;
      lavaSourceConversion: boolean;
      commandBlockOutput: boolean;
      forgiveDeadPlayers: boolean;
      playersNetherPortalCreativeDelay: number;
      doMobSpawning: boolean;
      maxEntityCramming: number;
      universalAnger: boolean;
      playersSleepingPercentage: number;
      snowAccumulationHeight: number;
      blockExplosionDropDecay: boolean;
      doImmediateRespawn: boolean;
      naturalRegeneration: boolean;
      doMobLoot: boolean;
      fallDamage: boolean;
      doEntityDrops: boolean;
      randomTickSpeed: number;
      playersNetherPortalDefaultDelay: number;
      spawnRadius: number;
      freezeDamage: boolean;
      sendCommandFeedback: boolean;
      doWardenSpawning: boolean;
      fireDamage: boolean;
      reducedDebugInfo: boolean;
      waterSourceConversion: boolean;
      projectilesCanBreakBlocks: boolean;
      announceAdvancements: boolean;
      drowningDamage: boolean;
      disableRaids: boolean;
      doWeatherCycle: boolean;
      mobExplosionDropDecay: boolean;
      doDaylightCycle: boolean;
      showDeathMessages: boolean;
      doTileDrops: boolean;
      doInsomnia: boolean;
      keepInventory: boolean;
      doLimitedCrafting: boolean;
      mobGriefing: boolean;
      commandModificationBlockLimit: number;
      doTraderSpawning: boolean;
      logAdminCommands: boolean;
      spectatorsGenerateChunks: boolean;
      doPatrolSpawning: boolean;
      maxCommandForkCount: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  userid: string;
  [k: string]: unknown;
}
